### ISSUE TITLE
1.18.2 build does not launch

### ISSUE THREAD

**Issue by SirBlockles** [pixelgamewizard/pgwbandedtorches#4]
Forge 40.0.36, Java 17.0.2 (also tested on forge 40.0.24, same log output)
game doesn't get past mojang screen, even if it's the only mod installed.
[latest.log](https://github.com/pixelgamewizard/pgwbandedtorches/files/8403960/latest.log) / [debug.log](https://github.com/pixelgamewizard/pgwbandedtorches/files/8403961/debug.log)

**Comment by pixelgamewizard** [comment]
Sorry for the problem, but thanks so much for the report. I've tried doing a clean forge install of 40.0.32 (what it was built with) and 40.0.36 (most recent right now), and neither seems to get past the mojang screen. I definitely have run the mod in 1.18.2 though, so I'm a bit confused what happened. I'm investigating and will try to get a fix posted asap.

**Comment by pixelgamewizard** [comment]
Well, in the end I didn't figure out why the version built with Forge 40.0.32 seemed to be having issues. I *did* end up getting things working again using:
- Forge 1.18.2 40.0.36
- A new version of Banded Torches (0.9.2022-04-03a) built with that version of Forge

I uploaded a new .jar to curseforge here: https://www.curseforge.com/minecraft/mc-mods/pixelgamewizards-banded-torches/files/3734185

Maybe give that a try?

**Comment by SirBlockles** [comment]
yeah, that fixed it. now working even alongside a full modpack.

**Comment by pixelgamewizard** [comment]
Excellent! Thanks again for the report, and for using the mod! :) Don't hesitate to let me know if you see anything else!
